CREATE TABLE "admin_users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "admin_users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "rsvp_responses" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"phone" varchar(50) NOT NULL,
	"pax" integer NOT NULL,
	"submitted_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wedding_details" (
	"id" serial PRIMARY KEY NOT NULL,
	"groom_name" varchar(255) NOT NULL,
	"bride_name" varchar(255) NOT NULL,
	"wedding_date" varchar(255) NOT NULL,
	"wedding_date_ms" varchar(255) NOT NULL,
	"ceremony_time_start" varchar(100) NOT NULL,
	"ceremony_time_end" varchar(100) NOT NULL,
	"reception_time_start" varchar(100) NOT NULL,
	"reception_time_end" varchar(100) NOT NULL,
	"venue_name" varchar(255) NOT NULL,
	"venue_address" text NOT NULL,
	"venue_google_maps_url" text DEFAULT '',
	"contact1_name" varchar(255) NOT NULL,
	"contact1_phone" varchar(50) NOT NULL,
	"contact1_label_en" varchar(255) NOT NULL,
	"contact1_label_ms" varchar(255) NOT NULL,
	"contact2_name" varchar(255) NOT NULL,
	"contact2_phone" varchar(50) NOT NULL,
	"contact2_label_en" varchar(255) NOT NULL,
	"contact2_label_ms" varchar(255) NOT NULL,
	"contact3_name" varchar(255) DEFAULT '',
	"contact3_phone" varchar(50) DEFAULT '',
	"contact3_label_en" varchar(255) DEFAULT '',
	"contact3_label_ms" varchar(255) DEFAULT '',
	"contact4_name" varchar(255) DEFAULT '',
	"contact4_phone" varchar(50) DEFAULT '',
	"contact4_label_en" varchar(255) DEFAULT '',
	"contact4_label_ms" varchar(255) DEFAULT '',
	"rsvp_deadline" varchar(255) NOT NULL,
	"rsvp_deadline_ms" varchar(255) NOT NULL,
	"event_type_en" varchar(255) NOT NULL,
	"event_type_ms" varchar(255) NOT NULL,
	"dress_code_en" varchar(255) NOT NULL,
	"dress_code_ms" varchar(255) NOT NULL,
	"parking_info_en" text NOT NULL,
	"parking_info_ms" text NOT NULL,
	"food_info_en" text NOT NULL,
	"food_info_ms" text NOT NULL,
	"invitation_note_en" text NOT NULL,
	"invitation_note_ms" text NOT NULL,
	"groom_title_en" varchar(255) DEFAULT '',
	"groom_title_ms" varchar(255) DEFAULT '',
	"bride_title_en" varchar(255) DEFAULT '',
	"bride_title_ms" varchar(255) DEFAULT '',
	"groom_father_name" varchar(255) DEFAULT '',
	"groom_mother_name" varchar(255) DEFAULT '',
	"bride_father_name" varchar(255) DEFAULT '',
	"bride_mother_name" varchar(255) DEFAULT '',
	"bismillah_text_en" text DEFAULT 'In the name of Allah, the Most Gracious, the Most Merciful',
	"bismillah_text_ms" text DEFAULT 'Dengan nama Allah Yang Maha Pemurah lagi Maha Penyayang',
	"with_pleasure_text_en" text DEFAULT 'With great pleasure, we',
	"with_pleasure_text_ms" text DEFAULT 'Dengan penuh kesyukuran, kami',
	"together_with_text_en" text DEFAULT 'together with',
	"together_with_text_ms" text DEFAULT 'bersama',
	"invitation_message_en" text DEFAULT 'cordially invite you to join us at the Wedding Reception of our beloved children',
	"invitation_message_ms" text DEFAULT 'menjemput Yang Berbahagia ke majlis perkahwinan anakanda kami',
	"cordially_invite_text_en" text DEFAULT 'Cordially invite you to join us at the Wedding Reception of our beloved children',
	"cordially_invite_text_ms" text DEFAULT 'Dengan hormatnya menjemput anda ke majlis perkahwinan anak kami',
	"updated_at" timestamp DEFAULT now() NOT NULL
);
